core/urls.py
from django.contrib import admin
from django.urls import path , include 

# image configuration in debuging True
from django.conf import settings
from django.conf.urls.static import static



# main url core 
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('echo.urls')),
    path('api-auth/', include('rest_framework.urls'))
]




# url routing image configuration in debuging True
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

echo/urls.py
"""
Echo Urls
"""
from django.urls import path
from . import views
app_name="echo"

urlpatterns = [
    path('', views.index , name="index"),
    path('api/', views.api , name="api"),
]

echo/models.py
from django.db import models

os_choices=(
  ('oscammand','oscammand'),
  ('mathcocommand','mathcocommand')
)


class OsTyper (models.Model):
  name=models.CharField(choices=os_choices,max_length=50)
  def __str__(self):
    return self.name



class OsCommand(models.Model):
  command_type=models.OneToOneField(OsTyper, on_delete=models.CASCADE,null=False,blank=False)
  command_name=models.CharField(max_length=50)
  paramet = models.ForeignKey('Parameter', on_delete=models.PROTECT ,null=True)

  def __str__(self):
    return self.command_name



class Parameter(models.Model):
  name=models.CharField(max_length=50)
  def __str__(self):
    return f"{self.name}"



class MathCommand(models.Model):
  command_type=models.OneToOneField(OsTyper, on_delete=models.CASCADE , null=False,blank=False)
  expression=models.CharField(max_length=50)

  def __str__(self):
    return self.expression

echo/views.py
from django.shortcuts import render , HttpResponse

from rest_framework.decorators import api_view
from rest_framework.response import Response
from .models import OsCommand , MathCommand
from .serializers import *


def index(request):
  return render(request,'echo/index.html')


@api_view(["GET"])
def api(request):
  queries=MathCommand.objects.all()
  queries_serializer=MathCommandSerializer(queries,many=True)
  return Response (queries_serializer.data)

# Create your views here.

templates/base.html
<!doctype html>
{% load static %}
<html>
<head>
  <meta charset="UTF-8">

  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <script src="https://cdn.tailwindcss.com"></script>

  <script src="{% static "js/tailwind.js" %}"></script>
</head>
<body class="bg-black">
  <header>
  <div class="w-fullscreen bg-black h-[100px] place-items-center content-center">

    <h1 class="text-white text-3xl content-center font-serif">
      Azma Group <a class="pl-5" style="color:red" href="{% url "echo:api" %}"> show api </a>
    </h1>
  </div>

  <div class=" bg-black h-[400px] ">
    {% block content %}{% endblock content %}
  </div>

</header>
 
  <footer class="  place-items-center text-center fixed bottom-0 right-0 left-0">
   <div class=" text-black w-[100%] bg-red  h-[60px] text-xl py-4 bg-red">
    <a class="py-[4px] text-yellow-100 font-mono" href="http://zamanianmehdi23blogproject.pythonanywhere.com/#"> &copy; Created by Mahdizamanian </a></div>
  </footer>

  <script src="{% static "js/websocket.js" %}"></script>
</body>
</html>

templates/echo/index.html
{% extends "base.html" %}
{% load static %}

{% block content %}

<div class="container mx-auto w-[100%] bg-white relative rounded h-[500px]">
  <textarea class=" w-[100%] rounded "  id="echo-log" cols="100" rows="20" ></textarea class="mx-auto"><br/>
  <input class="bg-sky-800 border w-[100%] h-[100px] h-200 absolute bottom-10 pl-9 text-black  bg-green" id="text-input" type="text" placeholder="text to server ..."/> <br/>
  <input class="button absolute bottom-10 w-[33%] h-[100px] right-0 bg-blue-200" id="text-submit" type="button" value="send"/>
</div>

{% endblock content %}